apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam_deployment
spec:
  selector:
    matchLabels:
      run: exam_deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: exam_deployment
    spec:
      containers:
      - name: exam_deployment
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80